package com.hit.memoryunits;
import java.io.Serializable;

/*
 * Page objects will be written into files, therefore need to implement the Serializable interface
 */
public class Page<T> implements Serializable
{
	private static final long serialVersionUID = -616017516154926601L;
	private T content;
	private long pageId;
	
	/*
	 * Constructor that gets the page content and page ID as arguments.
	 */
	public Page(T content, long pageId)
	{
		this.content = content;
		this.pageId = pageId;
	}
	
	public long getPageId()
	{
		return pageId;
	}

	public void setPageId(long pageId)
	{
		this.pageId = pageId;
	}

	public T getContent()
	{
		return content;
	}

	public void setContent(T content)
	{
		this.content = content;
	}

	/*
	 * Check if two pages are equal according to whether all the following match: same class, same content, same page ID. 
	 */
	@Override
	public boolean equals(Object otherPage)
	{
		boolean isEqual = false;
		
		if (otherPage.getClass() != this.getClass()) 
		{
			isEqual = false;
		}
		else if (((Page<?>) otherPage).getContent() != this.content)
		{
			isEqual = false;
		}
		else if (((Page<?>) otherPage).getPageId() == this.pageId)
		{
			isEqual = true;
		}
			
		return isEqual;
	}
	
	/*
	 * Each page has its unique pageID, therefore we can use the given hashcode generated by Long class
	 */
	@Override
	public int hashCode()
	{
		return Long.hashCode(pageId);
	}
	
	@Override
	public String toString()
	{
		return "Page Id is" + pageId + "\nAnd the content of the page is "+ content;
	}
}
